### ISSUE TITLE
release house and house/download pages

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/viewer-sinatra#15256]
# Problem

We currently have a Page for a Country, and a parallel Download page for that Country. These group together information for each Legislature in that Country. This gets confusing at times (particularly on the Download page), because we're cramming quite a lot onto them. Instead, we should create similar Pages at a per-Legislature level.

We will need to keep the primary per-Country page (as it's the primary entry point for a Country from various places), but we should be able to completely delete the per-Country download page (with suitable redirects in place).

We should, as normal, deliver this in small steps, but there are various mutual dependencies (as each of these pages will need to link to each other).

This issue captures each of the things that we know we need to do:
# Proposed Solution

Suggested that we release in this order:
### Step 1: New Pages (not yet linked)
- [x] Create a house/download page (#15245)
- [x] house page is published (#15246)
- [x] Ensure house/download links to House page (#15339)
- [x] Ensure House page links to Download page
- [ ] improve text about "other politicians in same country" at bottom of house page ~~#15259~~ (#15451)
### Step 2: Usable Live Pages (would like this week)
- [x] link to Legislature page from Country page #15255 
- [x] link to Legislature page from Term Table page (header bar)
- [ ] stop collapsing terms on download page #15243 
### Step 3: Post-live cleanup (should happen soon, but OK for there to be some delay)
- [ ] check no links exist/remain to country/download pages
- [ ] delete country/download pages and redirect (client-side: because gh-pages)) ~~#15261~~ (#15464 and #15466)
# Acceptance Criteria
- [ ] Working house and house/download pages, linked from Country and Term pages.
- [ ] No broken links on viewer-sinatra site and therefore on the static site.
# Not Required

n/a
# Prerequisites

See issues above.
# Related Issues

See issues above.
# Due Date

n/a (ASAP)
# Design?

No
# Text?

No
# Bloggable?

No
