### ISSUE TITLE
Migrate content from jekyll site

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/viewer-sinatra#336]
- [x] Add the map to the country list page (#170)
- [x] Extend the about page with new documentation (#102)
- [x] Replace CSV converter with information on all the different ways to contribute, until we get a direct CSV uploader (https://github.com/everypolitician/viewer-sinatra/issues/294)

**Comment by tmtmtmtm** [comment]
This is all done to a very basic level. Improving each is taken care of in the separate tickets.
